# Generated by Django 5.2.6 on 2025-09-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('Middle East', 'Middle East'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania')], default='Africa', max_length=50),
        ),
        migrations.AlterField(
            model_name='travelbookings',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='', max_length=20),
        ),
    ]
