# Generated by Django 5.2.6 on 2025-09-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_region_country_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
