# Generated by Django 5.2.6 on 2025-09-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_country_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
