# Generated by Django 5.2.6 on 2025-09-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_country_zip_code_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.AddField(
            model_name='country',
            name='zip_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
