# Generated by Django 5.2.6 on 2025-09-05 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_country_code_country_zip_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TravelBookings',
            new_name='TravelBooking',
        ),
    ]
