# Generated by Django 5.2.6 on 2025-09-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_travelbookings_travelbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelbooking',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='travelbooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='TravelBooking',
        ),
    ]
